name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        run: |
          # Add your deployment script here
          # For example, you can use SSH to copy the files to your EC2 instance
          # Replace the placeholders with your actual values
          ssh user@your-ec2-instance 'bash -s' < deploy_script.sh
